# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: psy_test
author: Corrado Caudek
logo: logo.png
copyright: "2024"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Bibtex config
bibtex_reference_style: author_year
bibtex_bibfiles: "references.bib"

# Information about where the book exists on the web
repository:
  url: https://github.com/ccaudek/psy_test # Online location of your book
  path_to_book: docs/ # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

footer_text: Created by <a href="https://ccaudek.github.io/caudeklab/">Corrado Caudek</a> using <a href="https://jupyterbook.org/">Jupyter Book</a>.

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "images/increasing.png"
  google_analytics_id: "G-VMXNE4BCDL"
  baseurl: "https://github.com/ccaudek/psy_test"
  use_repository_button     : false
  use_edit_page_button      : false
  use_issues_button         : false 
  baseurl: https://ccaudek.github.io/psy_test  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis: false

# Cache execution outputs
execute:
  execute_notebooks: cache

exclude_patterns:
  - "sandbox/*"

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise
