# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: cfa_book
author: Corrado Caudek
logo: logo.png
copyright: "2023"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Bibtex config
bibtex_reference_style: author_year
bibtex_bibfiles: "references.bib"

# Information about where the book exists on the web
repository:
  url: https://github.com/ccaudek/cfa_book_2023 # Online location of your book
  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "images/increasing.png"
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx_proof

